# Generated by Django 4.2.16 on 2025-10-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoDesenvolvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('unidade_secretaria', models.CharField(max_length=200, verbose_name='Unidade/Secretaria')),
                ('chefia_imediata', models.CharField(max_length=200, verbose_name='Chefia Imediata')),
                ('linguagem_ferramenta', models.CharField(max_length=255, verbose_name='Linguagem ou ferramenta que trabalha')),
                ('principal_desafio', models.TextField(verbose_name='Principal desafio enfrentado nos projetos/trabalho')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscrição de Desenvolvedor',
                'verbose_name_plural': 'Inscrições de Desenvolvedores',
            },
        ),
        migrations.DeleteModel(
            name='PrimeiroEscalao',
        ),
        migrations.DeleteModel(
            name='RedeTransformacaoDigital',
        ),
    ]
